service: hello-world

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}

# The functions section is only necessary if deploying a lambda
functions:
  hello:
    handler: index.hello

custom:
  s3_bucket_name: lambdapersistentdata01-${opt:stage}
  s3_versioning:
    qc: "Suspended"
    sbx: "Enabled"
    prod: "Enabled"
  a_secret: ${ssm:/ag/lsmwhat/asecret/${opt:stage}}
  
resources:
  - ${file(../../OW-CentralizedIaCModules/serverlessFramework/modules/s3.yml)}
  
