name: Deploy Lambda in Serverless

jobs:
  deploy:
    uses: OpsWrangler/OW-CentralizedActions/.github/workflows/deploy_lambda_in_serverless.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.ORG_AWS_DEFAULT_REGION }}
      GITHUB_TOKEN_1: ${{ secrets.ORG_GITHUB_TOKEN }}
    
on:
  push:
    branches:
      - main
    paths:
      - serverlessFramework/Lambda/**
  workflow_dispatch:  
